package lab4.jdbc;

import lab4.config.DbConfig;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public final class DatabaseBootstrap {
    private DatabaseBootstrap() {
    }

    public static synchronized void ensure(DbConfig config) throws Exception {
        Class.forName(config.getDriver());
        try (Connection connection = DriverManager.getConnection(config.getUrl(), config.getUser(), config.getPassword())) {
            if (!hasTable(connection, "PRODUCT")) {
                createSchema(connection);
            } else {
                createSchema(connection);
            }
            seed(connection);
        }
    }

    private static boolean hasTable(Connection connection, String tableName) throws SQLException {
        DatabaseMetaData meta = connection.getMetaData();
        try (ResultSet tables = meta.getTables(null, null, tableName.toUpperCase(), null)) {
            return tables.next();
        }
    }

    private static void createSchema(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS category (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL UNIQUE
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS manufacturer (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL UNIQUE
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS warehouse (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL UNIQUE,
                        address VARCHAR(160)
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS product (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(120) NOT NULL,
                        category_id INT NOT NULL,
                        manufacturer_id INT NOT NULL,
                        warehouse_id INT NOT NULL,
                        price DECIMAL(10, 2) NOT NULL,
                        quantity INT NOT NULL,
                        CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id),
                        CONSTRAINT fk_product_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES manufacturer(id),
                        CONSTRAINT fk_product_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse(id)
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS app_user (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        login VARCHAR(50) NOT NULL UNIQUE,
                        password_hash VARCHAR(128) NOT NULL,
                        user_role VARCHAR(20) NOT NULL
                    )
                    """);
        }
    }

    private static void seed(Connection connection) throws SQLException {
        if (count(connection, "product") > 0) {
            return;
        }
        int parts = findOrCreateName(connection, "category", "Комплектующие ПК");
        int network = findOrCreateName(connection, "category", "Сетевое оборудование");
        int logitech = findOrCreateName(connection, "manufacturer", "Logitech");
        int tplink = findOrCreateName(connection, "manufacturer", "TP-Link");
        int mainStock = findOrCreateWarehouse(connection, "Основной склад", "Ростов-на-Дону, Гагарина 1");

        insertProduct(connection, "Мышь M185", parts, logitech, mainStock, new BigDecimal("1290.00"), 18);
        insertProduct(connection, "Wi-Fi роутер Archer C6", network, tplink, mainStock, new BigDecimal("3890.00"), 7);
    }

    private static int count(Connection connection, String table) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) FROM " + table)) {
            resultSet.next();
            return resultSet.getInt(1);
        }
    }

    private static void insertProduct(Connection connection, String name, int categoryId, int manufacturerId,
                                      int warehouseId, BigDecimal price, int quantity) throws SQLException {
        String sql = """
                INSERT INTO product(name, category_id, manufacturer_id, warehouse_id, price, quantity)
                VALUES (?, ?, ?, ?, ?, ?)
                """;
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, name);
            statement.setInt(2, categoryId);
            statement.setInt(3, manufacturerId);
            statement.setInt(4, warehouseId);
            statement.setBigDecimal(5, price);
            statement.setInt(6, quantity);
            statement.executeUpdate();
        }
    }

    public static int findOrCreateName(Connection connection, String table, String name) throws SQLException {
        String selectSql = "SELECT id FROM " + table + " WHERE LOWER(name) = LOWER(?)";
        try (PreparedStatement statement = connection.prepareStatement(selectSql)) {
            statement.setString(1, name);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getInt("id");
                }
            }
        }

        String insertSql = "INSERT INTO " + table + "(name) VALUES (?)";
        try (PreparedStatement statement = connection.prepareStatement(insertSql, Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, name);
            statement.executeUpdate();
            try (ResultSet keys = statement.getGeneratedKeys()) {
                keys.next();
                return keys.getInt(1);
            }
        }
    }

    public static int findOrCreateWarehouse(Connection connection, String name, String address) throws SQLException {
        String selectSql = "SELECT id FROM warehouse WHERE LOWER(name) = LOWER(?)";
        try (PreparedStatement statement = connection.prepareStatement(selectSql)) {
            statement.setString(1, name);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    int id = resultSet.getInt("id");
                    if (address != null && !address.isBlank()) {
                        try (PreparedStatement update = connection.prepareStatement("UPDATE warehouse SET address = ? WHERE id = ?")) {
                            update.setString(1, address);
                            update.setInt(2, id);
                            update.executeUpdate();
                        }
                    }
                    return id;
                }
            }
        }

        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO warehouse(name, address) VALUES (?, ?)", Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, name);
            statement.setString(2, address == null ? "" : address);
            statement.executeUpdate();
            try (ResultSet keys = statement.getGeneratedKeys()) {
                keys.next();
                return keys.getInt(1);
            }
        }
    }
}
